name: tex
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  image_input: ^0.0.5
  lucide_icons: ^0.257.0
  permission_handler: ^11.3.1
  http: ^1.2.2
  uuid: ^4.5.1
  bcrypt: ^1.1.3
  floating_action_bubble_custom: ^1.0.0+2
  cloudinary_flutter: ^1.0.0
  cloudinary_url_gen: ^1.0.0
  shared_preferences: ^2.3.2
  sheet: ^1.0.0
  flutter_secure_storage: ^9.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SF-Pro.ttf
